#!/bin/bash
packages=(vulkan-devel glfw_wayland glm glslc shaderc)
sudo pacman --noconfirm --needed -S "${packages[@]}" || {
	echo 'Failed to install pacman packages.'
	exit 1
}
echo "DONE!"

# lsp for glsl
paru_packages=(glsl_analyzer)
paru --noconfirm --needed -S "${paru_packages[@]}" || {
	echo 'Failed to install paru packages.'
	exit 1
}
echo "DONE!"
