#!/bin/sh

# Jump words with ctrl arrowkeys
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

function yazycd() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}

bindkey -s '^o' '^uyazycd\n'
bindkey -s '^n' '^unvim .\n'
bindkey -s '^y' '^uyazi\n'
bindkey -s '^f' "^utmux-sessionizer\n"
bindkey -s '^b' "^utmux-sessionizer --no-database\n"
bindkey -s '^x' '^usource $ZSHRC\n'
bindkey -s '^p' '^uzathura-fzf\n'
