[pyprland]
plugins = [
  "scratchpads",
  "workspaces_follow_focus",
]

[scratchpads.gptbing]
  command= "flatpak run com.microsoft.Edge --app='https://www.bing.com/search?form=NTPCHB&q=Bing+AI&showconv=1'"
  animation= "fromTop"
  class_match=true
  class= "Microsoft-edge"
  margin= 70
  size= "50% 50%"
  lazy= true

[scratchpads.up-term]
  command= "alacritty --class dropterm-top"
  animation= "fromTop"
  unfocus= "hide"
  size= "50% 50%"
  lazy= true

[scratchpads.drop-term]
  command= "alacritty --class dropterm"
  animation= "fromBottom"
  unfocus= "hide"
  size= "50% 50%"
  lazy= true

[scratchpads.whatsapp]
  command= "chromium --app=https://web.whatsapp.com/"
  position= "25% 20%"
  size= "50% 60%"
  lazy= true

[scratchpads.telegram]
  command= "telegram-desktop"
  # position= "25% 20%"
  animation = "fromBottom"
  size= "50% 60%"
  class= "org.telegram.desktop"
  # class_match=true
  lazy= true

[scratchpads.volume]
  command= "pavucontrol"
  animation= "fromRight"
  lazy= true
  size= "15% 25%"

[scratchpads.discord]
  command= "discord"
  size= "50% 60%"
  animation=""
  class= "discord"
  class_match=true
  lazy= true


